export default {
  id: 'gaming',
  name: 'Game Ranks',
  icon: '🎮',
  color: '#f59e0b',
  dateField: 'date',
  defaultSort: { key: 'date', dir: 'desc' },
  columns: [
    {
      key: 'game',
      label: 'Game',
      type: 'text',
      required: true,
      placeholder: 'e.g. Smite 2',
    },
    {
      key: 'rank',
      label: 'Rank / SR',
      type: 'text',
      required: true,
      placeholder: 'e.g. Diamond I / 3400 SR',
    },
    {
      key: 'tier',
      label: 'Tier',
      type: 'select',
      options: ['Amber', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Obsidian', 'Master', 'Demigod', 'Deity'],
      badge: {
        Amber:    { bg: '#fef3c7', color: '#92400e' },
        Bronze:   { bg: '#fde8d0', color: '#7c2d12' },
        Silver:   { bg: '#e2e8f0', color: '#334155' },
        Gold:     { bg: '#fef9c3', color: '#713f12' },
        Platinum: { bg: '#ccfbf1', color: '#065f46' },
        Diamond:  { bg: '#dbeafe', color: '#1e40af' },
        Obsidian: { bg: '#ede9fe', color: '#3b0764' },
        Master:   { bg: '#f3e8ff', color: '#6b21a8' },
        Demigod:  { bg: '#fee2e2', color: '#7f1d1d' },
        Deity:    { bg: '#fefce8', color: '#713f12' },
      },
    },
    {
      key: 'wins',
      label: 'Wins',
      type: 'number',
      placeholder: '0',
    },
    {
      key: 'losses',
      label: 'Losses',
      type: 'number',
      placeholder: '0',
    },
    {
      key: 'date',
      label: 'Date',
      type: 'date',
      required: true,
    },
    {
      key: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Session notes...',
    },
  ],
}
