export default {
  id: 'gaming',
  name: 'Game Ranks',
  icon: '🎮',
  color: '#f59e0b',
  dateField: 'date',
  defaultSort: { key: 'date', dir: 'desc' },
  columns: [
    {
      key: 'game',
      label: 'Game',
      type: 'text',
      required: true,
      placeholder: 'e.g. Valorant',
    },
    {
      key: 'rank',
      label: 'Rank / Elo',
      type: 'text',
      required: true,
      placeholder: 'e.g. Diamond 2 / 1850',
    },
    {
      key: 'tier',
      label: 'Tier',
      type: 'select',
      options: ['Iron', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Master', 'Grandmaster', 'Challenger'],
      badge: {
        Iron: { bg: '#f3f4f6', color: '#374151' },
        Bronze: { bg: '#fef3c7', color: '#78350f' },
        Silver: { bg: '#e5e7eb', color: '#374151' },
        Gold: { bg: '#fef9c3', color: '#713f12' },
        Platinum: { bg: '#d1fae5', color: '#065f46' },
        Diamond: { bg: '#dbeafe', color: '#1e40af' },
        Master: { bg: '#ede9fe', color: '#5b21b6' },
        Grandmaster: { bg: '#fce7f3', color: '#9d174d' },
        Challenger: { bg: '#fee2e2', color: '#7f1d1d' },
      },
    },
    {
      key: 'wins',
      label: 'Wins',
      type: 'number',
      placeholder: '0',
    },
    {
      key: 'losses',
      label: 'Losses',
      type: 'number',
      placeholder: '0',
    },
    {
      key: 'date',
      label: 'Date',
      type: 'date',
      required: true,
    },
    {
      key: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Session notes...',
    },
  ],
}
