export default {
  id: 'jobs',
  name: 'Job Applications',
  icon: '💼',
  color: '#0ea5e9',
  dateField: 'appliedDate',
  defaultSort: { key: 'appliedDate', dir: 'desc' },
  columns: [
    {
      key: 'company',
      label: 'Company',
      type: 'text',
      required: true,
      placeholder: 'e.g. Google',
    },
    {
      key: 'role',
      label: 'Role',
      type: 'text',
      required: true,
      placeholder: 'e.g. Software Engineer',
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      options: ['Applied', 'Phone Screen', 'Technical', 'Onsite', 'Offer', 'Rejected', 'Withdrawn'],
      badge: {
        Applied: { bg: '#dbeafe', color: '#1e40af' },
        'Phone Screen': { bg: '#fef3c7', color: '#92400e' },
        Technical: { bg: '#ede9fe', color: '#5b21b6' },
        Onsite: { bg: '#fce7f3', color: '#9d174d' },
        Offer: { bg: '#d1fae5', color: '#065f46' },
        Rejected: { bg: '#fee2e2', color: '#991b1b' },
        Withdrawn: { bg: '#f3f4f6', color: '#374151' },
      },
    },
    {
      key: 'appliedDate',
      label: 'Applied Date',
      type: 'date',
      required: true,
    },
    {
      key: 'followUpDate',
      label: 'Follow-up Date',
      type: 'date',
    },
    {
      key: 'salary',
      label: 'Salary Range',
      type: 'text',
      placeholder: 'e.g. $120k–$150k',
    },
    {
      key: 'source',
      label: 'Source',
      type: 'select',
      options: ['LinkedIn', 'Indeed', 'Company Website', 'Referral', 'Recruiter', 'Other'],
    },
    {
      key: 'jobUrl',
      label: 'Job URL',
      type: 'url',
      placeholder: 'https://...',
    },
    {
      key: 'notes',
      label: 'Notes',
      type: 'textarea',
      placeholder: 'Interview notes, contacts...',
    },
  ],
}
